global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'ecommerce-services'
    static_configs:
      - targets:
          - 'api-gateway-container:8080'
          - 'order-service-container:8300'
          - 'payment-service-container:8400'
          - 'product-service-container:8500'
          - 'shipping-service-container:8600'
          - 'user-service-container:8700'
          - 'favourite-service-container:8800'
