global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'ecommerce-dev'
    environment: 'development'

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - '/etc/prometheus/alert.rules.yml'

scrape_configs:
  # Solo los 3 microservicios que est√°n corriendo
  - job_name: 'ecommerce-services'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    static_configs:
      - targets:
          - 'ecommerce-microservice-backend-app-product-service-container-1:8500'
          - 'ecommerce-microservice-backend-app-order-service-container-1:8300'
          - 'ecommerce-microservice-backend-app-payment-service-container-1:8400'
        labels:
          environment: 'dev'
